language: php

php:
  - 5.6

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install

after_success:
  - build/scripts/standards
  - build/scripts/publish.sh
